In [64]:
!pip3 install requests beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /Users/ato/Library/Python/3.9/lib/python/site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in /Users/ato/Library/Python/3.9/lib/python/site-packages (4.14.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from requests) (2025.10.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from requests) (2.5.0)
Requirement already satisfied: soupsieve>1.2 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4) (4.15.0)
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [65]:

import requests 
from bs4 import BeautifulSoup 
 
url = 'https://www.kinokuniya.co.jp/f/dsd-101005021--' 
res = requests.get(url) 
  
res.text 
soup = BeautifulSoup(res.text, 'html.parser') 
  
book_div = soup.select_one('#main_contents > form > div.list_area_wrap')   
books_a_span = book_div.select('a img.mb05,span.sale_price') 
  
pairs = list(zip(books_a_span[0::2], books_a_span[1::2])) 
book = pairs[0] 
  
names, prices = book 
name = names.get('alt', '').strip() 
  
price = prices.get_text(strip=True) 
  
price = int(price.replace('¥', '').replace(',', '')) 
  
one_data = { 
    'name': name, 
    'price': price 
}

AttributeError: 'NoneType' object has no attribute 'select'

In [66]:
import requests 
from bs4 import BeautifulSoup 
url = 'https://www.kinokuniya.co.jp/f/dsd-101005021--' 
res = requests.get(url) 
  
res.text 
soup = BeautifulSoup(res.text, 'html.parser') 
  
book_div = soup.select_one('.list_area_wrap') 
  
books_a_span = book_div.select('a img.mb05,span.sale_price') 
  
pairs = list(zip(books_a_span[0::2], books_a_span[1::2])) 
  
#book = pairs[0] 
  
data = [] 
for book in pairs: 
  
    names, prices = book 
    name = names.get('alt', '').strip() 
  
    price = prices.get_text(strip=True) 
  
    price = int(price.replace('¥', '').replace(',', '')) 
  
    one_data = { 
        'name': name, 
        'price': price 
    } 
  
    data.append(one_data)

In [67]:
data

[{'name': 'ショパン コミック版\u3000世界の伝記', 'price': 1320},
 {'name': 'テーレマコス', 'price': 2640},
 {'name': '最高の夏休み', 'price': 3960},
 {'name': 'ＩＮＮＵ（５）', 'price': 792},
 {'name': 'クソキモカタルシス(話売り)\u3000#9', 'price': 165},
 {'name': 'ディグイット\u3000分冊版（７）', 'price': 220},
 {'name': 'ああ、生きているって素晴らしい【タテヨミ】 第63話 挑戦 ジャンプコミックスDIGITAL', 'price': 61},
 {'name': 'いろいろなハナシ 1', 'price': 176},
 {'name': 'ヒトグイ\u300045話', 'price': 77},
 {'name': 'ヒトグイ\u300056話', 'price': 77},
 {'name': '浮世島 (1) バンブーコミックス', 'price': 880},
 {'name': 'げきおこシュリケン', 'price': 176},
 {'name': '不夜城の一等星 2', 'price': 250},
 {'name': '予知視 76 ズズズキュン！', 'price': 110},
 {'name': '不夜城の一等星 3', 'price': 250},
 {'name': 'オドのための備忘録 Ⅰ', 'price': 550},
 {'name': '奈楽荘\u3000第27話\u3000地獄-急-【タテヨミ】 ホンコミックス', 'price': 61},
 {'name': 'アカテン教師 梨本小鉄 3', 'price': 880},
 {'name': 'みっしょん！！（５）', 'price': 792},
 {'name': '到達のアクタ（２）', 'price': 792}]

In [68]:
!pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/ato/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ato/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [69]:
import pandas as pd 
df = pd.DataFrame(data)

In [55]:
df.head()

                name  price
0   ショパン コミック版　世界の伝記   1320
1             テーレマコス   2640
2             最高の夏休み   3960
3            ＩＮＮＵ（５）    792
4  クソキモカタルシス(話売り)　#9    165

In [62]:
df = df.rename(columns={'name': '書名', 'price': '価格'})

In [61]:
df.head()

                  書名    価格
0   ショパン コミック版　世界の伝記  1320
1             テーレマコス  2640
2             最高の夏休み  3960
3            ＩＮＮＵ（５）   792
4  クソキモカタルシス(話売り)　#9   165

In [60]:
df.to_csv('books.csv', index=False, encoding='utf-8-sig')